import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { BookService } from 'src/app/seller-dashboard/book.service';
import { ImageService } from 'src/app/services/image.service';
import { ApibookService } from './apibook.service';
 
@Component({
  selector: 'app-add-book',
  templateUrl: './add-book.component.html',
  styleUrls: ['./add-book.component.css']
})
export class AddBookComponent {
  autoGeneratedBookId: string | undefined;
  selectedImage: string | undefined;
  bookForm: FormGroup;
  bookDetails: any = {}; 
  constructor(private fb: FormBuilder,private router: Router,private bookService: BookService,public imageService: ImageService,private apibook:ApibookService) {
    this.bookForm = this.fb.group({
      bookName: ['', [Validators.required]],
      authorName: ['', [Validators.required]],
      description: ['', [Validators.required]],
      price: [0, [Validators.required]],
      image: ['', [Validators.required]]
    });
  }
 
addBook() {
  const bookData = {
    bookName: this.bookForm.value.bookName,
    authorName: this.bookForm.value.authorName,
    description: this.bookForm.value.description,
    price: this.bookForm.value.price,
    image: this.bookForm.value.image
  };
 
  this.apibook.addBook(bookData).subscribe({
    next:(response: any) => {
      console.log('Book added successfully:', response);
      alert('Book Added Successfully');
      this.router.navigate(['/seller-dashboard']);
    },
    error:
    (error: any) => {
      console.error('Error adding book:', error);
    }
  }
  );
}   
}